name: Release

on:
  push:
    tags:
      - '20*'

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Get the version
        id: vars
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup Maven Settings
        uses: whelk-io/maven-settings-xml-action@v18
        with:
          repositories: '[{ "id": "github", "url": "https://maven.pkg.github.com/gymbossbot/*" }]'
          servers: '[{"id": "github", "username": "artem-snopkov", "password": "${{secrets.MAVEN_REPO_PWD}}"}]'

      - name: Set Version
        run: mvn versions:set -DnewVersion=${{steps.vars.outputs.VERSION}}

      - name: Build with Maven
        run: mvn deploy

      - name: Notify
        uses: yanzay/notify-telegram@v0.1.0
        if: always()
        with:
          chat: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          status: ${{ job.status }}